### ISSUE TITLE
Restore Pillow decency before  Home Assistant 2024.8.0

### ISSUE THREAD

**Issue by watermarkhu** [sca075/mqtt_vacuum_camera#231]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

Currently incompatible with Home Assistant 2024.8.0b3 due to pillow version requirement. 

![Screenshot_20240806-084936](https://github.com/user-attachments/assets/6303b89f-0a88-4811-8ccc-d65fe9cdac9a)

### What version of an integration has described problem?

v2024.07.4

### What vacuum model do you have problems with?

*

### What type of platform you use?

VEMLinux (Virtual Machine) such as Proxmox, VMWare, etc.

### What version of Home Assistant do you use?

2024.8.0b3

### What type of installation are you running?

Home Assistant OS

### Function, that in your opinion is creating the issue.

Not sure / none of the above.

**Comment by sca075** [comment]
@watermarkhu thanks, the next release will contain the required Pillow version control. I had to remove it temporally because there was another user with HA < 2024.8.0 that had to run a test for us (I mean all of us). If I had kept in the manifest.json the "pillow==10.4.0" in the requirements the Camera wouldn't start. Please use / downgrade to beta 2 and with the next release will be working.

**Comment by watermarkhu** [comment]
@sca075 no problem! Seems you are already aware :)
